### ISSUE TITLE
'AM_PROG_CC_C_O' in 'configure.ac'

### ISSUE THREAD

**Issue by hanbaobao2005** [flix-/keeto#13]
download the latest keeto on CentOS7 and execute autogen.sh, it met an issue：
tests/Makefile.am:3: warning: compiling '../src/keeto-config.c' in subdir requires 'AM_PROG_CC_C_O' in 'configure.ac'

I guess the solution could refer to https://github.com/cryptotronix/hashlet/issues/1

**Comment by flix-** [comment]
Hey,

thanks for reporting! I added the macro (again) although it is obsolete since automake 1.14. But as automake < 1.14 is still out there...
