### ISSUE TITLE
make check with error

### ISSUE THREAD

**Issue by gainskills** [flix-/keeto#14]
After fixed https://github.com/flix-/keeto/issues/13
execute command : 'make check'

The error log:

Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73840]: [E] failed to validate syslog facility: option 'syslog_facility', value 'foo' (invalid syslog facility)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73840]:[E] failed to validate syslog facility: option 'syslog_facility', value 'foo' (invalid syslog facility)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73841]: [E] failed to validate ldap uri: option 'ldap_uri', value 'http://xy.z' (invalid ldap uri)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73841]:[E] failed to validate ldap uri: option 'ldap_uri', value 'http://xy.z' (invalid ldap uri)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73842]: [E] failed to validate boolean: option 'ldap_starttls', value '2' (value must be either 0 or 1)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73842]:[E] failed to validate boolean: option 'ldap_starttls', value '2' (value must be either 0 or 1)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73843]: [E] failed to validate ldap dn: option 'ldap_bind_dn', value 'cn?foo,bar' (Decoding error)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73843]:[E] failed to validate ldap dn: option 'ldap_bind_dn', value 'cn?foo,bar' (Decoding error)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73844]: [E] failed to validate ldap search timeout: option 'ldap_search_timeout', value '0' (value must be > 0)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73844]:[E] failed to validate ldap search timeout: option 'ldap_search_timeout', value '0' (value must be > 0)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73845]: [E] failed to validate boolean: option 'ldap_strict', value '2' (value must be either 0 or 1)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73845]:[E] failed to validate boolean: option 'ldap_strict', value '2' (value must be either 0 or 1)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73846]: [E] failed to validate ldap dn: option 'ldap_ssh_server_search_base', value '/dev/null' (Decoding error)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
keeto[73846]:[E] failed to validate ldap dn: option 'ldap_ssh_server_search_base', value '/dev/null' (Decoding error)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73847]: [E] failed to convert value: option 'ldap_ssh_server_search_scope', value 'ALL' (invalid value)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73847]:[E] failed to convert value: option 'ldap_ssh_server_search_scope', value 'ALL' (invalid value)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73848]: [E] failed to validate cert store dir: option 'cert_store_dir', value 'not-existent' (No such file or directory)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73848]:[E] failed to validate cert store dir: option 'cert_store_dir', value 'not-existent' (No such file or directory)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73849]: [E] failed to validate boolean: option 'check_crl', value '2' (value must be either 0 or 1)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73849]:[E] failed to validate boolean: option 'check_crl', value '2' (value must be either 0 or 1)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73850]: [E] failed to compile uid regex: option 'uid_regex', value '[' (2)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73850]:[E] failed to compile uid regex: option 'uid_regex', value '[' (2)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73853]: [E] failed to get file status: file './file_readable/not-existent' (No such file or directory)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73853]:[E] failed to get file status: file './file_readable/not-existent' (No such file or directory)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73862]: [E] './file_readable/dir-none' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73862]:[E] './file_readable/dir-none' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73863]: [E] './file_readable/dir-read' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73863]:[E] './file_readable/dir-read' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73864]: [E] './file_readable/dir-read-write' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73864]:[E] './file_readable/dir-read-write' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73865]: [E] './file_readable/dir-read-execute' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73865]:[E] './file_readable/dir-read-execute' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73866]: [E] './file_readable/dir-read-write-execute' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73866]:[E] './file_readable/dir-read-write-execute' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73867]: [E] './file_readable/dir-write' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73867]:[E] './file_readable/dir-write' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73868]: [E] './file_readable/dir-write-execute' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73868]:[E] './file_readable/dir-write-execute' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73869]: [E] './file_readable/dir-execute' is not a regular file
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73869]:[E] './file_readable/dir-execute' is not a regular file
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73907]: [E] failed to parse dn 'www.xy.z' (Decoding error)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73907]:[E] failed to parse dn 'www.xy.z' (Decoding error)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73909]: [E] certificate not valid (unable to get local issuer certificate)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73909]:[E] certificate not valid (unable to get local issuer certificate)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73910]: [E] certificate not valid (certificate has expired)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73910]:[E] certificate not valid (certificate has expired)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73911]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73911]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73912]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73912]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73913]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73913]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73914]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73914]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73915]: [E] certificate not valid (certificate has expired)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73915]:[E] certificate not valid (certificate has expired)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73920]: [E] certificate not valid (unable to get local issuer certificate)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73920]:[E] certificate not valid (unable to get local issuer certificate)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73921]: [E] certificate not valid (certificate has expired)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73921]:[E] certificate not valid (certificate has expired)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:00 EST):
keeto[73922]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:00 ...
 keeto[73922]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:01 EST):
keeto[73923]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:01 ...
 keeto[73923]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:01 EST):
keeto[73924]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:01 ...
 keeto[73924]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:01 EST):
keeto[73925]: [E] certificate not valid (unsupported certificate purpose)
Message from syslogd@ftpsrv1 at Feb  5 11:56:01 ...
 keeto[73925]:[E] certificate not valid (unsupported certificate purpose)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:01 EST):
keeto[73926]: [E] certificate not valid (certificate has expired)
Message from syslogd@ftpsrv1 at Feb  5 11:56:01 ...
 keeto[73926]:[E] certificate not valid (certificate has expired)
Broadcast message from systemd-journald@ftpsrv1.cnrsec.net (Sun 2017-02-05 11:56:01 EST):
keeto[73927]: [E] certificate not valid (certificate revoked)

Message from syslogd@ftpsrv1 at Feb  5 11:56:01 ...
 keeto[73927]:[E] certificate not valid (certificate revoked)
FAIL: keeto-check
make[4]: Entering directory `/tmp/keeto-develop/tests'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/tmp/keeto-develop/tests'
============================================================================
Testsuite summary for keeto 0.2.0-beta
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to seroland86@gmail.com
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/tmp/keeto-develop/tests'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/tmp/keeto-develop/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/keeto-develop/tests'
make: *** [check-recursive] Error 1

**Comment by flix-** [comment]
I couldn't reproduce the error on a centos7 machine :/ Could you paste the content of tests/test-suite.log so i can see which testcase produced that error?

Thanks for your help!

**Comment by hanbaobao2005** [comment]
[Uploading test-suite.zip…]()
Here the log, Thanks,

**Comment by flix-** [comment]
Thanks for the log file. My assumption is that you are running 'make check' as root user. Is that correct? If so please run with user priviledges as described here: https://keeto.readthedocs.io/en/latest/getting_started.html. Please give me a short ping if that solves this issue.

**Comment by hanbaobao2005** [comment]
Yes, you're right. I ran 'make check' as a root user. I ran it gain with user privilege and it looks good:
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0

Really appreciate your help.
